DKDEPEND(opengl)
DKDEPEND(agl)
DKDEPEND(libx11-dev)
DKDEPEND(shlwapi.lib)
DKDEPEND(zlib)
DKDEPEND(giflib)
DKDEPEND(libpng)
DKDEPEND(libjpeg-turbo)
DKDEPEND(libwebp)
DKDEPEND(tiff)
DKDEPEND(glew)
DKDEPEND(sdl)
DKDEPEND(sdl_image)
DKDEPEND(rmlui)

DKINCLUDE(${DKPROJECT})
#DKINCLUDE(${DKPROJECT}/shell/include)

